import "./Testimonials.css";

import person1 from "./person1.png";
import person2 from "./person2.png";
import person3 from "./person3.png";
import person4 from "./person4.png";
import person5 from "./person5.png";
import person6 from "./person6.png";

const testimonials = [
  {
    image: person1,
    quote:
      "CODEXA completely changed the way our engineering team builds software. What used to take weeks of planning, coding and debugging is now accomplished in just a few hours. It's become an essential part of our development workflow.",
    name: "Ethan Brooks",
    role: "CTO, NovaStack",
  },
  {
    image: person2,
    quote:
      "Our developers use CODEXA every day. It generates production-ready code, understands complex requirements and allows our team to focus on solving business problems instead of repetitive boilerplate.",
    name: "David Chen",
    role: "VP Engineering, CloudScale",
  },
  {
    image: person3,
    quote:
      "The quality of the applications generated by CODEXA genuinely surprised us. The frontend, backend and database all work together seamlessly. It feels like having another senior engineer on the team.",
    name: "Michael Turner",
    role: "Founder & CEO, PixelForge",
  },
  {
    image: person4,
    quote:
      "We shipped our SaaS platform nearly three times faster using CODEXA. The AI handles repetitive engineering work so our developers can focus on building features that truly matter.",
    name: "Ryan Cooper",
    role: "Co-Founder, LaunchFlow",
  },
  {
    image: person5,
    quote:
      "From architecture planning to deployment, CODEXA consistently produces clean, scalable and maintainable code. It has become our team's default starting point for every project.",
    name: "Daniel Foster",
    role: "Lead Software Architect, TechVerse",
  },
  {
    image: person6,
    quote:
      "CODEXA has dramatically improved our team's productivity. Instead of spending days configuring projects, we immediately begin building products and delivering value to customers.",
    name: "James Walker",
    role: "Engineering Manager, BrightAI",
  },
];

function Testimonials() {
  return (
    <section className="testimonials">
      <div className="testimonials-container">
        <div className="testimonials-header">
          <h2>The new way to build software.</h2>
        </div>

        <div className="testimonials-grid">
          {testimonials.map((item, index) => (
            <div className="testimonial-card" key={index}>
              <p className="testimonial-text">
                "{item.quote}"
              </p>

              <div className="testimonial-user">
                <img
                  src={item.image}
                  alt={item.name}
                  className="testimonial-avatar"
                />

                <div className="testimonial-info">
                  <h4>{item.name}</h4>
                  <span>{item.role}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default Testimonials;